<a href="https://colab.research.google.com/github/varshitfauzdar/AIML_Hands_on/blob/main/K_Nearest_Neighbor_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Business Problem - Predict the Price of Bangalore House

**Using** K Nearest Neighbor Regression - Supervised Machine Learning Algorithm

In [2]:
# Load Libraries
import pandas as pd

In [3]:
# Load Data
path = r"https://drive.google.com/uc?export=download&id=1xxDtrZKfuWQfl-6KA9XEd_eatitNPnkB"
df = pd.read_csv(path)

df.head()

,bath,balcony,price,total_sqft_int,bhk,price_per_sqft,area_typeSuper built-up Area,area_typeBuilt-up Area,area_typePlot Area,availability_Ready To Move,...,location_Kalena Agrahara,location_Horamavu Agara,location_Vidyaranyapura,location_BTM 2nd Stage,location_Hebbal Kempapura,location_Hosur Road,location_Horamavu Banaswadi,location_Domlur,location_Mahadevpura,location_Tumkur Road
0,3.0,2.0,150.0,1672.0,3,8971.291866,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,3.0,3.0,149.0,1750.0,3,8514.285714,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
2,3.0,2.0,150.0,1750.0,3,8571.428571,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,2.0,2.0,40.0,1250.0,2,3200.000000,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,2.0,2.0,83.0,1200.0,2,6916.666667,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0

In [4]:
# Split Data
X = df.drop('price', axis=1)
y = df['price']

print('Shape of X = ', X.shape)
print('Shape of y = ', y.shape)

Shape of X =  (7120, 107)
Shape of y =  (7120,)

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=51)

print('Shape of X_train = ', X_train.shape)
print('Shape of y_train = ', y_train.shape)
print('Shape of X_test = ', X_test.shape)
print('Shape of y_test = ', y_test.shape)

Shape of X_train =  (5696, 107)
Shape of y_train =  (5696,)
Shape of X_test =  (1424, 107)
Shape of y_test =  (1424,)

##K Nearest Neighbor Regression - ML Model Training

In [6]:
from sklearn.neighbors import KNeighborsRegressor

regressor = KNeighborsRegressor(n_neighbors=5)
regressor.fit(X_train, y_train)

regressor.score(X_test, y_test)

0.8858214084886539

## Predict the value of Home

In [7]:
X_test.iloc[-1, :]

regressor.predict([X_test.iloc[-1, :]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  warnings.warn(

array([184.4])

In [8]:
y_test.iloc[-1]

y_pred = regressor.predict(X_test)
y_pred

array([ 77.378,  39.808, 120.2  , ...,  33.405,  63.   , 184.4  ])

In [9]:
y_test

2435     80.00
3113     40.00
426     120.00
1124     79.00
1161     45.00
         ...
2078     28.34
6855     84.00
4381     32.00
3862     63.00
43      180.00
Name: price, Length: 1424, dtype: float64

In [12]:
regressor.score(X_test,y_test)

0.8858214084886539

In [27]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X_train)
x_train_sc = sc.transform(X_train)
x_test_sc = sc.transform(X_test)

In [28]:
regressor.fit(x_train_sc, y_train)

KNeighborsRegressor()

In [29]:
y_pred = regressor.predict(x_test_sc)

In [30]:
regressor.score(x_test_sc,y_test)

0.9112892295498807

###This is wrong bcz:


model always First argument → features (X)

Second argument → true labels (y)

In [31]:
regressor.score(y_pred,y_test)

ValueError: Expected 2D array, got 1D array instead:
array=[ 78.     52.09  123.4   ...  34.764  48.258 155.6  ].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.