<a href="https://colab.research.google.com/github/varshitfauzdar/AIML_Hands_on/blob/main/Polynomial_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
from sklearn import datasets

In [3]:
path = r"https://drive.google.com/uc?export=download&id=1xxDtrZKfuWQfl-6KA9XEd_eatitNPnkB"
df = pd.read_csv(path)
df.head()

,bath,balcony,price,total_sqft_int,bhk,price_per_sqft,area_typeSuper built-up Area,area_typeBuilt-up Area,area_typePlot Area,availability_Ready To Move,...,location_Kalena Agrahara,location_Horamavu Agara,location_Vidyaranyapura,location_BTM 2nd Stage,location_Hebbal Kempapura,location_Hosur Road,location_Horamavu Banaswadi,location_Domlur,location_Mahadevpura,location_Tumkur Road
0,3.0,2.0,150.0,1672.0,3,8971.291866,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,3.0,3.0,149.0,1750.0,3,8514.285714,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
2,3.0,2.0,150.0,1750.0,3,8571.428571,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,2.0,2.0,40.0,1250.0,2,3200.000000,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,2.0,2.0,83.0,1200.0,2,6916.666667,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0

# Split data

In [4]:
X = df.drop("price",axis = 1)
Y = df["price"]
X.shape , Y.shape

((7120, 107), (7120,))

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size=0.2, shuffle = True, random_state= 42)

In [6]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((5696, 107), (1424, 107), (5696,), (1424,))

# Feature Scaling

In [7]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scale = scaler.fit_transform(X_train)
X_test_scale = scaler.fit_transform(X_test)

In [8]:
X_train_scale

array([[-0.44422611,  0.54630035,  0.07232582, ..., -0.04782807,
        -0.05138463, -0.04782807],
       [ 0.6879045 ,  1.83462341,  0.17729421, ..., -0.04782807,
        -0.05138463, -0.04782807],
       [-0.44422611, -0.74202271, -0.50500027, ..., -0.04782807,
        -0.05138463, -0.04782807],
       ...,
       [-0.44422611,  0.54630035, -0.35279612, ..., -0.04782807,
        -0.05138463, -0.04782807],
       [ 0.6879045 ,  0.54630035,  0.98030232, ..., -0.04782807,
        -0.05138463, -0.04782807],
       [-0.44422611,  0.54630035, -0.12186568, ..., -0.04782807,
        -0.05138463, -0.04782807]])

In [9]:
X_test_scale

array([[-0.45268298,  0.58887587, -0.43419624, ..., -0.07028523,
        -0.05935999, -0.07028523],
       [-0.45268298,  0.58887587, -0.35013875, ..., -0.07028523,
        -0.05935999, -0.07028523],
       [-0.45268298, -0.74933961, -0.37454253, ..., -0.07028523,
        -0.05935999, -0.07028523],
       ...,
       [-0.45268298,  0.58887587, -0.45453273, ..., -0.07028523,
        -0.05935999, -0.07028523],
       [-0.45268298, -0.74933961, -0.88973363, ..., -0.07028523,
        -0.05935999, -0.07028523],
       [-0.45268298, -0.74933961, -0.51825373, ..., -0.07028523,
        -0.05935999, -0.07028523]])

In [10]:
# Polynomial Linear Regression - ML model Traing

In [11]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [12]:
poly = PolynomialFeatures(degree = 2)
X_train_poly = poly.fit_transform(X_train_scale)
X_test_poly = poly.fit_transform(X_test_scale)

In [13]:
lr = LinearRegression()
lr.fit(X_train_poly,y_train)

LinearRegression()

In [14]:
lr.score(X_train_poly,y_train)

1.0

In [15]:
y_pred = lr.predict(X_test_poly)

In [17]:
y_test

960      47.0
132      60.0
2431     65.0
2229    325.0
4503     60.0
        ...
4970     48.0
553     205.0
1397     56.5
4056     26.0
1817     49.0
Name: price, Length: 1424, dtype: float64

In [16]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)*100

95.98294565761185

In [18]:
mse = mean_squared_error(y_test,y_pred)
mse

456.0621911166839

In [20]:
rmse = np.sqrt(mse)
rmse

np.float64(21.3556126373533)