<a href="https://colab.research.google.com/github/varshitfauzdar/AIML_Hands_on/blob/main/Randome_Forest_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Business Problem - Predict the Price of Bangalore House

Using Randome Forest Regression - Supervised Machine Learning Algorithm

In [1]:
# Load Libraries
import pandas as pd

In [2]:
# Load Data
path = r"https://drive.google.com/uc?export=download&id=1xxDtrZKfuWQfl-6KA9XEd_eatitNPnkB"
df = pd.read_csv(path)

df.head()

,bath,balcony,price,total_sqft_int,bhk,price_per_sqft,area_typeSuper built-up Area,area_typeBuilt-up Area,area_typePlot Area,availability_Ready To Move,...,location_Kalena Agrahara,location_Horamavu Agara,location_Vidyaranyapura,location_BTM 2nd Stage,location_Hebbal Kempapura,location_Hosur Road,location_Horamavu Banaswadi,location_Domlur,location_Mahadevpura,location_Tumkur Road
0,3.0,2.0,150.0,1672.0,3,8971.291866,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,3.0,3.0,149.0,1750.0,3,8514.285714,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
2,3.0,2.0,150.0,1750.0,3,8571.428571,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,2.0,2.0,40.0,1250.0,2,3200.000000,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,2.0,2.0,83.0,1200.0,2,6916.666667,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0

In [3]:
# Split Data"""

X = df.drop('price', axis=1)
y = df['price']

print('Shape of X = ', X.shape)
print('Shape of y = ', y.shape)

Shape of X =  (7120, 107)
Shape of y =  (7120,)

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=51)

print('Shape of X_train = ', X_train.shape)
print('Shape of y_train = ', y_train.shape)
print('Shape of X_test = ', X_test.shape)
print('Shape of y_test = ', y_test.shape)

Shape of X_train =  (5696, 107)
Shape of y_train =  (5696,)
Shape of X_test =  (1424, 107)
Shape of y_test =  (1424,)

In [10]:
#Randome Forest Regression - ML Model Training"""

from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor(n_estimators=100, criterion='squared_error')
regressor.fit(X_train, y_train)

regressor.score(X_test, y_test)

0.8924287038261918

In [11]:
regressor_100 = RandomForestRegressor(n_estimators=500, criterion='squared_error')
regressor_100.fit(X_train, y_train)

regressor_100.score(X_test, y_test)

0.8935561314796608

In [12]:
# Predict the value of Home"""

X_test.iloc[-1, :]

bath                               2.000000
balcony                            0.000000
total_sqft_int                  1566.000000
bhk                                2.000000
price_per_sqft                 11494.252874
                                   ...
location_Hosur Road                0.000000
location_Horamavu Banaswadi        0.000000
location_Domlur                    0.000000
location_Mahadevpura               0.000000
location_Tumkur Road               0.000000
Name: 43, Length: 107, dtype: float64

In [13]:
regressor.predict([X_test.iloc[-1, :]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

array([177.46])

In [14]:
y_test.iloc[-1]

np.float64(180.0)

In [15]:
y_pred = regressor.predict(X_test)
y_pred

array([ 79.8341 ,  39.9468 , 119.6    , ...,  33.38135,  63.0971 ,
       177.46   ])

In [16]:
y_test

2435     80.00
3113     40.00
426     120.00
1124     79.00
1161     45.00
         ...
2078     28.34
6855     84.00
4381     32.00
3862     63.00
43      180.00
Name: price, Length: 1424, dtype: float64